name: esphome_connect_app
description: Connect to ESPHome devices and control them

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  esphome_connect:
    git:
      url: https://github.com/Marc-R2/esphome_connect_package.git

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  flutter_launcher_icons: "^0.13.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/512w/icon.png"
  min_sdk_android: 16 # android min sdk min:16, default 21
  web:
    generate: true
  windows:
    generate: true
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    image_path: "assets/512w/icon_patch.png"
    generate: true

flutter:
  uses-material-design: true
